name: "Универсальная статья"
description: "Базовый шаблон для создания статей на любую тему"
version: "1.0"
language: "ru"

variables:
  - name: "topic"
    description: "Тема статьи"
    required: true
  - name: "target_audience"
    description: "Целевая аудитория"
    default: "широкая аудитория"
  - name: "style"
    description: "Стиль написания"
    default: "информативный и доступный"
  - name: "word_count"
    description: "Примерное количество слов"
    default: "1500-2000"

prompt: |
  Напиши подробную и интересную статью на тему: {topic}
  
  Требования к статье:
  - Целевая аудитория: {target_audience}
  - Стиль: {style}
  - Объем: {word_count} слов
  - Язык: русский
  
  Структура статьи:
  1. Введение (зацепка, постановка проблемы)
  2. Основная часть (раскрытие темы с примерами)
  3. Практические советы или выводы
  4. Заключение
  
  Критерии качества:
  - Информативность и полезность
  - Легкость восприятия
  - Логическая структура
  - Практическая ценность
  - Интересные факты или примеры
  
  Не используй заголовок в самом тексте - он будет добавлен отдельно.
  Пиши естественно, избегай штампов и слишком формального стиля.
  Добавь конкретные примеры и полезные детали.

frontmatter_template:
  title: "{topic}"
  description: "Подробная статья о {topic}"
  publish: false
  created_date: "{current_date}"
  tags: 
    - "статья"
  featured_image: ""
  slug: ""

image_keywords:
  - "{topic}"
  - "концепция"
  - "технология"
  - "современность" 