name: "Universal Article"
description: "Base template for creating articles on any topic"
version: "1.0"
language: "en"

variables:
  - name: "topic"
    description: "Article topic"
    required: true
  - name: "target_audience"
    description: "Target audience"
    default: "general audience"
  - name: "style"
    description: "Writing style"
    default: "informative and accessible"
  - name: "word_count"
    description: "Approximate word count"
    default: "1500-2000"

prompt: |
  Write a comprehensive and engaging article on the topic: {topic}
  
  Article requirements:
  - Target audience: {target_audience}
  - Style: {style}
  - Length: {word_count} words
  - Language: English
  
  Article structure:
  1. Introduction (hook, problem statement)
  2. Main body (topic development with examples)
  3. Practical advice or conclusions
  4. Conclusion
  
  Quality criteria:
  - Informative and useful content
  - Easy to understand
  - Logical structure
  - Practical value
  - Interesting facts or examples
  
  Do not include the title in the text itself - it will be added separately.
  Write naturally, avoid clichés and overly formal style.
  Add specific examples and useful details.

frontmatter_template:
  title: "{topic}"
  description: "Comprehensive article about {topic}"
  publish: false
  created_date: "{current_date}"
  tags: 
    - "article"
  featured_image: ""
  slug: ""

image_keywords:
  - "{topic}"
  - "concept"
  - "technology"
  - "modern" 