# Bot Configuration
bot:
  name: "Content Generator Bot"
  version: "1.0.0"
  description: "AI-powered content generator for Obsidian Blogger"
  
# Telegram Settings
telegram:
  polling: true
  webhook: false
  parse_mode: "Markdown"
  
# AI Providers Configuration
ai:
  default_provider: "openai"
  providers:
    openai:
      model: "gpt-4o-mini"
      max_tokens: 4000
      temperature: 0.7
      presence_penalty: 0.1
      frequency_penalty: 0.1


# Content Generation Settings
content:
  default_language: "ru"
  min_word_count: 800
  max_word_count: 3000
  quality_threshold: 0.8
  auto_publish: false
  include_images: true
  
# Image Settings
images:
  provider: "unsplash"
  orientation: "landscape"
  size: "large"
  fallback_enabled: true
  
# Commands Configuration
commands:
  - command: "start"
    description: "Start working with the bot"
  - command: "generate"
    description: "Generate new article"
  - command: "templates"
    description: "List available templates"
  - command: "drafts"
    description: "Manage drafts"
  - command: "settings"
    description: "Generation settings"
  - command: "help"
    description: "Help and instructions"
  - command: "status"
    description: "System and AI providers status"
  - command: "sync"
    description: "Sync files with blog"
  - command: "publish"
    description: "Publish draft to blog"
    
# Rate Limiting
rate_limiting:
  enabled: true
  requests_per_hour: 10
  requests_per_day: 50
  burst_limit: 3 