import { BaseAIProvider } from './baseProvider.js';
import { logger } from '../utils/logger.js';
import axios from 'axios';

/**
 * Anthropic (Claude) Provider для генерации контента
 */
export class AnthropicProvider extends BaseAIProvider {
    constructor(config) {
        super(config);
        
        if (!config.apiKey) {
            throw new Error('Anthropic API key is required');
        }
        
        this.apiKey = config.apiKey;
        this.model = config.model || 'claude-3-haiku-20240307';
        this.maxTokens = config.max_tokens || 4000;
        this.temperature = config.temperature || 0.7;
        this.baseURL = 'https://api.anthropic.com/v1';
        
        logger.debug(`Anthropic Provider initialized with model: ${this.model}`);
    }

    async generate(prompt, options = {}) {
        try {
            // Валидация промпта
            if (!this.validatePrompt(prompt)) {
                throw new Error('Invalid prompt provided');
            }

            logger.info(`Anthropic: Starting generation with model ${this.model}`);
            logger.debug(`Prompt length: ${prompt.length} characters`);

            const response = await axios.post(
                `${this.baseURL}/messages`,
                {
                    model: this.model,
                    max_tokens: options.maxTokens || this.maxTokens,
                    temperature: options.temperature || this.temperature,
                    messages: [
                        {
                            role: 'user',
                            content: `Ты профессиональный копирайтер, который создает качественные и интересные статьи на русском языке. Пиши естественно, информативно и увлекательно.\n\n${prompt}`
                        }
                    ]
                },
                {
                    headers: {
                        'Content-Type': 'application/json',
                        'x-api-key': this.apiKey,
                        'anthropic-version': '2023-06-01'
                    }
                }
            );

            const content = response.data.content[0]?.text;
            
            if (!content) {
                throw new Error('No content generated by Anthropic');
            }

            logger.success(`Anthropic: Content generated successfully`);

            return this.formatResponse(content, {
                model: this.model,
                tokensUsed: response.data.usage?.output_tokens || this.estimateTokens(content),
                inputTokens: response.data.usage?.input_tokens,
                outputTokens: response.data.usage?.output_tokens,
                stopReason: response.data.stop_reason
            });

        } catch (error) {
            logger.error('Anthropic generation failed:', error);
            return this.handleError(error);
        }
    }

    async isAvailable() {
        try {
            if (!this.hasApiKey()) {
                return false;
            }

            // Простой тест запрос для проверки доступности
            const response = await axios.post(
                `${this.baseURL}/messages`,
                {
                    model: this.model,
                    max_tokens: 1,
                    messages: [{ role: 'user', content: 'Test' }]
                },
                {
                    headers: {
                        'Content-Type': 'application/json',
                        'x-api-key': this.apiKey,
                        'anthropic-version': '2023-06-01'
                    }
                }
            );

            return response.status === 200;
        } catch (error) {
            logger.warn('Anthropic availability check failed:', error);
            return false;
        }
    }

    /**
     * Оценка стоимости запроса для Claude
     */
    estimateCost(inputTokens, outputTokens) {
        // Примерные цены для Claude 3 (на декабрь 2024)
        const pricing = {
            'claude-3-haiku-20240307': {
                input: 0.00025,  // $ за 1K токенов
                output: 0.00125  // $ за 1K токенов
            },
            'claude-3-sonnet-20240229': {
                input: 0.003,
                output: 0.015
            },
            'claude-3-opus-20240229': {
                input: 0.015,
                output: 0.075
            }
        };

        const modelPricing = pricing[this.model] || pricing['claude-3-haiku-20240307'];
        
        const inputCost = (inputTokens / 1000) * modelPricing.input;
        const outputCost = (outputTokens / 1000) * modelPricing.output;
        
        return {
            inputCost,
            outputCost,
            totalCost: inputCost + outputCost,
            currency: 'USD'
        };
    }

    handleError(error) {
        const baseError = super.handleError(error);

        // Специфичные ошибки Anthropic
        if (error.response?.data?.error?.type === 'authentication_error') {
            return {
                ...baseError,
                error: 'INVALID_API_KEY',
                message: 'Неверный Anthropic API ключ'
            };
        }

        if (error.response?.data?.error?.type === 'rate_limit_error') {
            return {
                ...baseError,
                error: 'RATE_LIMIT',
                message: 'Превышен лимит запросов к Anthropic'
            };
        }

        if (error.response?.data?.error?.type === 'invalid_request_error') {
            return {
                ...baseError,
                error: 'INVALID_REQUEST',
                message: 'Неверный запрос к Anthropic API'
            };
        }

        return baseError;
    }
} 